name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pre-commit
      - name: Lint
        run: pre-commit run --all-files --show-diff-on-failure

  test-release-crate:
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        crate: [leptos-fluent, leptos-fluent-macros]
    name: Test crate release of ${{ matrix.crate }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v --dry-run -p ${{ matrix.crate }}

  release-crate:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        crate: [leptos-fluent, leptos-fluent-macros]
    name: Release crate ${{ matrix.crate }}
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v -p ${{ matrix.crate }}
